# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skael < Formula
  desc "Control plane for AI agent skills"
  homepage "https://skael.dev"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/skael_0.11.0_darwin_amd64.tar.gz"
      sha256 "1c9363e4aca308f4f64ce70ab25cf95338d6cad959800843af16db12d6293a30"

      define_method(:install) do
        bin.install "skael"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/skael_0.11.0_darwin_arm64.tar.gz"
      sha256 "e365eb88a5246d04c339bdb75cbf2b3294863176b24c172625604a036bf28205"

      define_method(:install) do
        bin.install "skael"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/skael_0.11.0_linux_amd64.tar.gz"
      sha256 "bb64f0a3a14f544f87cbbf86a2b1f9eff0f721c60936425dbefcb2b7a858fb71"
      define_method(:install) do
        bin.install "skael"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/skael_0.11.0_linux_arm64.tar.gz"
      sha256 "1bedaee31b9ee818b76e75193034bf417541237ed9f1d4505b5cdf18ace4e810"
      define_method(:install) do
        bin.install "skael"
      end
    end
  end

  test do
    system "#{bin}/skael", "version"
  end
end
