# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skael < Formula
  desc "Control plane for AI agent skills"
  homepage "https://skael.dev"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/skael_0.13.0_darwin_amd64.tar.gz"
      sha256 "cf734089a2304eeb4b9e7311a391e04de2c423e207b509226cbf233f025c5f5a"

      define_method(:install) do
        bin.install "skael"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/skael_0.13.0_darwin_arm64.tar.gz"
      sha256 "d1e8ea4144305f3e3440f733d40ea25818434f3f6363b9c042e88eecab7ae118"

      define_method(:install) do
        bin.install "skael"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/skael_0.13.0_linux_amd64.tar.gz"
      sha256 "8ca7317ead590acee3726641bbf0c9e76da3608934e04040f5f7d1d2c9f9da79"
      define_method(:install) do
        bin.install "skael"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/skael_0.13.0_linux_arm64.tar.gz"
      sha256 "94cb218e2dc744e740918e86ddb5466b7e8122f2a134e55bc4cfa2fac392e124"
      define_method(:install) do
        bin.install "skael"
      end
    end
  end

  test do
    system "#{bin}/skael", "version"
  end
end
