# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkaelReleases < Formula
  desc "Control plane for AI agent skills"
  homepage "https://skael.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alternayte/skael-releases/releases/download/v0.1.0/skael_0.1.0_darwin_amd64.tar.gz"
      sha256 "5e92aecc76280d406aacd76b98ced09d05eb3b66331963955fcdd5bd52bfe4aa"

      define_method(:install) do
        bin.install "skael"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alternayte/skael-releases/releases/download/v0.1.0/skael_0.1.0_darwin_arm64.tar.gz"
      sha256 "8cf4096532e4e5b9a87088edc7f33a44e56c60809587329020e1fe9da8c43890"

      define_method(:install) do
        bin.install "skael"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alternayte/skael-releases/releases/download/v0.1.0/skael_0.1.0_linux_amd64.tar.gz"
      sha256 "4a012c90ec03cbb562ad7cf60386363366b1e988502a5ba5260a94df2f474663"
      define_method(:install) do
        bin.install "skael"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alternayte/skael-releases/releases/download/v0.1.0/skael_0.1.0_linux_arm64.tar.gz"
      sha256 "45a1594081dff4aafe501b3ffa4097019fe9d1cf4ed44d587844af700f5494be"
      define_method(:install) do
        bin.install "skael"
      end
    end
  end

  test do
    system "#{bin}/skael", "version"
  end
end
