# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whetstone < Formula
  desc "Authoring and evaluation toolkit for AI agent skills"
  homepage "https://skael.dev"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/whetstone_0.13.0_darwin_amd64.tar.gz"
      sha256 "d37cb9c33344bd233f6ea25f8b45e76f64f429373d3f1a495a38fab39cad8ae2"

      define_method(:install) do
        bin.install "whetstone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/whetstone_0.13.0_darwin_arm64.tar.gz"
      sha256 "71cb78f5c7286278338f31ba7a96bffa5b043852f0e8f2e847e85b46a7e4ae2c"

      define_method(:install) do
        bin.install "whetstone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/whetstone_0.13.0_linux_amd64.tar.gz"
      sha256 "b5742757a2116c5d626ab9dbcd075c6cd3928c60e3f8c9aeac2120a2ef0894b8"
      define_method(:install) do
        bin.install "whetstone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.13.0/whetstone_0.13.0_linux_arm64.tar.gz"
      sha256 "657bfd1f80777cd8211c669d451a1f5464174c3d11e6c6b8777ac2d916e7ac93"
      define_method(:install) do
        bin.install "whetstone"
      end
    end
  end

  test do
    system "#{bin}/whetstone", "version"
  end
end
