# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whetstone < Formula
  desc "Authoring and evaluation toolkit for AI agent skills"
  homepage "https://skael.dev"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/whetstone_0.11.0_darwin_amd64.tar.gz"
      sha256 "5d1aa71d91ac3f80192b19f57d4448b9dac19fc7d635939117a87a12c6f5a026"

      define_method(:install) do
        bin.install "whetstone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/whetstone_0.11.0_darwin_arm64.tar.gz"
      sha256 "8eb46d0ec0964b546a0231116ba128b9e1c7e69ee0efd01ae4b5cc76edf7c9dc"

      define_method(:install) do
        bin.install "whetstone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/whetstone_0.11.0_linux_amd64.tar.gz"
      sha256 "b377474b20d4a7be6f6b7708550bb54790632b8f0af1ef46340d668941f288ff"
      define_method(:install) do
        bin.install "whetstone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skael-dev/skael/releases/download/v0.11.0/whetstone_0.11.0_linux_arm64.tar.gz"
      sha256 "8b634dd79ecfa5157c1984a31220a76860f36f2af9acba48acbd148e934746b6"
      define_method(:install) do
        bin.install "whetstone"
      end
    end
  end

  test do
    system "#{bin}/whetstone", "version"
  end
end
