# This file was generated by GoReleaser. DO NOT EDIT.
cask "skael" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/skael"]
    end
  end

  version "0.15.1"

  on_macos do
    on_arm do
      sha256 "a464ef7ad88c455b0bfc36192cb073edba16c24572ac5088cf96923244ca024d"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "17d15ad7a7430728835cb1a7adec7b356d36d5f2a1fa6d9ec124616154e18fb6"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3af2e81f8b3c3f4de7731503f16654aa42cc4db256b60a62cc1716335fddfb4d"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d524d89efa12e68a1b880838d57ac2eedad9d6ce86ebe4e4b9f6b6a0b196b52"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skael"
  desc "Control plane for AI agent skills"
  homepage "https://skael.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skael"

  # No zap stanza required
end
