# This file was generated by GoReleaser. DO NOT EDIT.
cask "skael" do
  version "0.15.0"

  on_macos do
    on_arm do
      sha256 "eda0c694b92b06ae086db3c933c7d7b86dd648c7c9ceff3efdc02607f31a6d61"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf5392b2a7281371795ae130c695f84f8fa8ed27c9c55fbede0104e89ac7bde8"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bc49aee34e324ca4db532b797780e8d9b59277812fd9cd3adf144e9ea9819a46"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f843f7fafd256ffe162e8794edc75e5889c7d683e3496f0f54bbcf3e6ef42a2f"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/skael_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skael"
  desc "Control plane for AI agent skills"
  homepage "https://skael.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skael"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skael"]
    end
  end

  # No zap stanza required
end
