# This file was generated by GoReleaser. DO NOT EDIT.
cask "whetstone" do
  version "0.15.0"

  on_macos do
    on_arm do
      sha256 "2e5ae45c7404d370bf1f07a5995b226a79ad8a375935c64fd3b84fc04eec4585"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "219fcaf49201e587d1f9f603faa49baae6ce26513504e9a18ee199c9ba5a57f2"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b33955a4cc1abccb3f1497c87cc40f822fa8d3a3a5c158820c60af64a81c72d3"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7880ad412eb63ce196cc4bfd7550134ca87edfe3f04392f308feeb2e60752826"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_linux_amd64.tar.gz"
    end
  end

  name "whetstone"
  desc "Authoring and evaluation toolkit for AI agent skills"
  homepage "https://skael.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whetstone"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whetstone"]
    end
  end

  # No zap stanza required
end
