# This file was generated by GoReleaser. DO NOT EDIT.
cask "whetstone" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/whetstone"]
    end
  end

  version "0.15.1"

  on_macos do
    on_arm do
      sha256 "83f7522d0f647ad3a476eeafbc10d5a34008858dc5e0aab571b1c2df9e59859c"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c1240ee60d692eb92208c75c5a58a50ced3309e0c31c28bae0c5d38e8d77815"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a98d0ffa53493c3d54b7d6df9a21e59c2515ac726cf66eadf49cef81be0735b4"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdc0737e2bec434cf809d2683115e5f198ee5100c6e8db79ac393ca81dfb60d4"
      url "https://github.com/skael-dev/skael/releases/download/v#{version}/whetstone_#{version}_linux_amd64.tar.gz"
    end
  end

  name "whetstone"
  desc "Authoring and evaluation toolkit for AI agent skills"
  homepage "https://skael.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whetstone"

  # No zap stanza required
end
